#!/usr/bin/env python3
"""
Prove the hover preview draws the page's graphics, not only its text.

Kate's preview calls paintTextLine, which draws text lines -- correct for a
text editor, where text is the entire content. A web page is not text, and a
16px icon beside a label is often the only thing that says what a row is. The
preview had no graphics at all, which is what this covers.

Each graphic in the fixture carries a `data-id`, which survives cloning. The
test resolves each one's real document position, converts it to a position on
the strip, hovers there, and asks whether that specific graphic turned up --
rather than guessing a fraction of the page and hoping.

For inline SVG it also checks the *computed fill*, which only resolves if the
clone is genuinely in this document's cascade. That is the assertion that
catches a regression to serialising SVGs into data URLs, which is how this was
first attempted: it loses the page's stylesheet, so `fill: currentColor` icons
come out blank, and its image load cannot be relied on to settle from a content
script.

    python3 test/verify_graphics.py
"""
import json
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from harness import SRC, fixture_server, launch_firefox, stop_firefox  # noqa: E402

PAGE = "/graphics.html"
# The label each graphic's row carries, for the "drawn exactly once" check.
# Empty where the graphic has no text of its own.
LABEL = {"bg-text": "LABEL-IN-BG"}

TARGETS = ["red-svg", "green-svg", "blue-svg", "orange-img", "purple-img",
           "bg-img", "bg-text", "bg-pseudo", "bg-cell", "teal-canvas",
           "teal-svg", "dark-img"]

# Elements that must NOT be mapped at all. Each is hovered on its own document
# position, so if the rule that excludes it were removed it would be in the
# preview and this would see it -- rather than checking at whatever position
# the target loop happened to finish on, which would always pass.
EXCLUDED = {"sticky-note": "STICKY-MUST-NOT-APPEAR",
            "fixed-note": "FIXED-MUST-NOT-APPEAR",
            "hidden-note": "HIDDEN-MUST-NOT-APPEAR",
            "faded-note": "FADED-MUST-NOT-APPEAR"}

# Find a graphic's position, converted to a fraction of the strip, so the test
# can aim at it rather than guess.
LOCATE = r"""
const cb = arguments[arguments.length - 1];
const id = arguments[0];
const el = document.querySelector(`[data-id="${id}"]`);
if (!el) { cb({err: "not found"}); return; }
const r = el.getBoundingClientRect();
const doc = document.scrollingElement;
cb({
  docY: r.top + window.scrollY + r.height / 2,
  docHeight: doc.scrollHeight,
  tag: el.tagName,
});
"""

HOVER = r"""
const done = arguments[arguments.length - 1];
const frac = arguments[0];
const id = arguments[1];
const strip = document.querySelector(".vugluscr .minimap");
if (!strip) { done({err: "no strip"}); return; }
const sr = strip.getBoundingClientRect();

function move() {
  strip.dispatchEvent(new PointerEvent("pointermove", {
    clientX: sr.left + sr.width / 2, clientY: sr.top + sr.height * frac,
    bubbles: true, cancelable: true, pointerId: 1, isPrimary: true
  }));
}

// Past Kate's 250ms first-appearance delay, then move again so this measures
// the steady state.
move();
setTimeout(() => {
  move();
  setTimeout(() => {
    const pop = document.querySelector(".scrollpeak-magnifier");
    if (!pop) { done({err: "no preview"}); return; }
    const stage = pop.querySelector(".scrollpeak-magnifier__stage");
    if (!stage) { done({err: "no stage"}); return; }
    const clone = stage.querySelector(`[data-id="${id}"]`);
    const lines = stage.querySelectorAll(".scrollpeak-magnifier__line").length;
    let fill = null;
    if (clone) {
      const shaped = clone.querySelector
        ? clone.querySelector("rect, circle, path, span")
        : null;
      if (shaped) fill = getComputedStyle(shaped).fill;
    }
    done({
      open: pop.classList.contains("is-open"),
      found: !!clone,
      tag: clone ? clone.tagName : null,
      width: clone ? Math.round(clone.getBoundingClientRect().width) : null,
      fill, lines,
      stageIds: [...stage.querySelectorAll("[id]")].map(e => e.id).length,
      // The clone is the page, so it keeps the page's own text -- which is
      // now drawn by the browser rather than reconstructed, and appears
      // exactly once.
      cloneText: clone ? clone.textContent.trim() : null,
      // How many times that graphic's text appears in the whole preview.
      labelCount: clone
        ? stage.textContent.split(clone.textContent.trim() || "\u0000").length - 1
        : 0,
      // ...but content generated by CSS is not a text node, so the text pass
      // never sees it and only the clone can reproduce it.
      before: clone ? getComputedStyle(clone, "::before").content : null,
      bg: clone ? getComputedStyle(clone).backgroundColor : null,
      // How many times the label appears in the preview, which is how many
      // times it is drawn. arguments[2] is the label.
      labelHits: arguments[2]
        ? stage.textContent.split(arguments[2]).length - 1
        : 0,
    });
  }, 350);
}, 450);
"""


def main():
    failures = []

    def check(name, cond, detail=""):
        print(f"  [{'PASS' if cond else 'FAIL'}] {name:44} {detail}")
        if not cond:
            failures.append(name)

    with fixture_server() as server:
        # Overridable so a deliberate bug can be reinstated in a copy of src/
        # and this same test run against it.
        proc, m = launch_firefox(sys.argv[1] if len(sys.argv) > 1 else SRC)
        try:
            m.cmd("WebDriver:Navigate", {"url": server.fixtures + PAGE})
            time.sleep(4)

            print("aim at each graphic and check the preview shows it")
            for tid in TARGETS:
                r = m.cmd("WebDriver:ExecuteAsyncScript",
                          {"script": LOCATE, "args": [tid], "scriptTimeout": 20000})
                loc = r.get("value", r)
                if "err" in loc:
                    check(f"{tid}", False, loc["err"])
                    continue
                # The strip maps position linearly onto the document, so this
                # is where the cursor has to be for that graphic to be centred.
                frac = min(0.97, max(0.03, loc["docY"] / loc["docHeight"]))
                r = m.cmd("WebDriver:ExecuteAsyncScript",
                          {"script": HOVER, "args": [frac, tid, LABEL.get(tid, "")],
                           "scriptTimeout": 40000})
                d = r.get("value", r)
                if "err" in d:
                    check(f"{tid}", False, d["err"])
                    continue
                shown = d["found"] and d["width"] and d["width"] > 3
                extra = ""
                if d["tag"] == "svg" and d["fill"]:
                    extra = f"fill={d['fill']}"
                elif d["tag"] == "CANVAS":
                    extra = f"{d['width']}px wide"
                check(f"shown: {tid}", shown,
                      f"{d['tag']} {d['width']}px {extra}")

                # The double-render case. On Wikipedia's usage-share table 778
                # of the links carry a background-image, so each one's label was
                # cloned whole and drawn a second time on top of the text run.
                if LABEL.get(tid):
                    # The graphic keeps the page's own text, and the preview
                    # renders it once -- by the browser, as part of the page's
                    # layout, rather than a reconstruction laid over the top.
                    check(f"{tid}'s label is present", d["cloneText"], repr(d["cloneText"]))
                    check(f"{tid}'s label is drawn exactly once",
                          d["labelHits"] == 1, f"{d['labelHits']} times")
                if tid == "bg-cell":
                    # The colour comes from `tr:first-child td:first-child`, a
                    # rule about the cell's place in the document. A clone keeps
                    # the classes but not the place, so without carrying the
                    # computed value across the cell comes out colourless --
                    # white rows where the page has green, amber and red ones.
                    check("a positional background is carried onto the clone",
                          d["bg"] == "rgb(212, 244, 180)", str(d["bg"]))
                    check("and it keeps the page's own text",
                          d["cloneText"] == "CELL", repr(d["cloneText"]))
                if tid == "bg-pseudo":
                    # CSS-generated content is not a text node, so stripping
                    # DOM text must not take the ::before with it.
                    check("the clone keeps its CSS-generated ::before",
                          d["before"] and ">>" in d["before"], str(d["before"]))

            print("\nhidden and pinned content renders as the page renders it")
            # The preview is a clone of the page now, so these elements are
            # *present* -- what has to hold is that they render the way the page
            # renders them, and are not un-hidden or pinned somewhere wrong.
            r = m.cmd("WebDriver:ExecuteScript", {"script": r"""
                const stage = document.querySelector(".scrollpeak-magnifier__stage");
                const out = {};
                for (const el of stage.querySelectorAll("[data-id]")) {
                  const cs = getComputedStyle(el);
                  out[el.getAttribute("data-id")] = {
                    visibility: cs.visibility, opacity: cs.opacity,
                    display: cs.display, position: cs.position,
                  };
                }
                return out;
            """, "args": []})
            d = r.get("value", r)
            check("hidden content is still hidden",
                  d.get("hidden-note", {}).get("visibility") == "hidden",
                  str(d.get("hidden-note")))
            check("zero-opacity content is still transparent",
                  d.get("faded-note", {}).get("opacity") == "0",
                  str(d.get("faded-note")))
            # A viewport-pinned overlay has no document position, so it is taken
            # out: otherwise a cookie banner sits pinned to the top of every
            # preview of the whole page.
            check("a fixed overlay is removed",
                  d.get("fixed-note", {}).get("display") == "none",
                  str(d.get("fixed-note")))
            check("sticky content stays where it flows",
                  d.get("sticky-note", {}).get("visibility") == "visible",
                  str(d.get("sticky-note")))

            print("\nno duplicate ids leaked into the page")
            r = m.cmd("WebDriver:ExecuteScript", {"script": r"""
                const stage = document.querySelector(".scrollpeak-magnifier__stage");
                return stage ? [...stage.querySelectorAll("[id]")].map(e => e.id) : [];
            """, "args": []})
            ids = r.get("value", r)
            check("clones carry no id attributes", not ids, str(ids))

            print("\nthe map never takes the page's graphics colours")
            r = m.cmd("WebDriver:ExecuteScript", {"script": r"""
                const map = document.querySelector(".scrollpeak-map");
                const d = map.getContext("2d").getImageData(0, 0, map.width, map.height).data;
                let red = 0, green = 0;
                for (let i = 0; i < d.length; i += 4) {
                  if (d[i+3] === 0) continue;
                  if (Math.abs(d[i]-192) < 26 && Math.abs(d[i+1]-57) < 26) red++;
                  if (Math.abs(d[i]-39) < 26 && Math.abs(d[i+1]-174) < 26) green++;
                }
                return {red, green, w: map.width};
            """, "args": []})
            d = r.get("value", r)
            # This is a short page, so the map is the block renderer and the
            # images are hollow ink outlines. The fixture's saturated colours
            # -- the red and green squares -- must not reach the map either
            # way: the graphics are content, not the palette.
            check("image colours do not leak into the map",
                  d["red"] == 0 and d["green"] == 0,
                  f"red={d['red']} green={d['green']} in a {d['w']}px map")
        finally:
            stop_firefox(proc)

    print()
    if failures:
        print("FAILED: " + ", ".join(failures))
        return 1
    print("the preview shows text, inline SVG, images, canvas and backgrounds")
    return 0


if __name__ == "__main__":
    sys.exit(main())
